export const tiposCalle = [
  { name: 'CARRETERA', value: 'CARRETERA' },
  { name: 'PRIVADA', value: 'PRIVADA' },
  { name: 'CALLE', value: 'CALLE' },
  { name: 'BOULEVARD', value: 'BOULEVARD' },
  { name: 'PROLONGACION', value: 'PROLONGACION' },
  { name: 'AVENIDA', value: 'AVENIDA' },
];

export const estadosDeLaRepublica = [
  { name: 'Aguascalientes', value: 'AGUASCALIENTES' },
  { name: 'Baja California', value: 'BAJA-CALIFORNIA' },
  { name: 'Baja California Sur', value: 'BAJA-CALIFORNIA-SUR' },
  { name: 'Campeche', value: 'CAMPECHE' },
  { name: 'Chiapas', value: 'CHIAPAS' },
  { name: 'Chihuahua', value: 'CHIHUAHUA' },
  { name: 'CDMX', value: 'CIUDAD-DE-MEXICO' },
  { name: 'Coahuila', value: 'COAHUILA' },
  { name: 'Colima', value: 'COLIMA' },
  { name: 'Durango', value: 'DURANGO' },
  { name: 'Guanajuato', value: 'GUANAJUATO' },
  { name: 'Guerrero', value: 'GUERRERO' },
  { name: 'Hidalgo', value: 'HIDALGO' },
  { name: 'Jalisco', value: 'JALISCO' },
  { name: 'Estado de México', value: 'ESTADO-DE-MEXICO' },
  { name: 'Michoacán', value: 'MICHOACAN' },
  { name: 'Morelos', value: 'MORELOS' },
  { name: 'Nayarit', value: 'NAYARIT' },
  { name: 'Nuevo León', value: 'NUEVO-LEON' },
  { name: 'Oaxaca', value: 'OAXACA' },
  { name: 'Puebla', value: 'PUEBLA' },
  { name: 'Querétaro', value: 'QUERETARO' },
  { name: 'Quintana Roo', value: 'QUINTANA-ROO' },
  { name: 'San Luis Potosí', value: 'SAN-LUIS-POTOSI' },
  { name: 'Sinaloa', value: 'SINALOA' },
  { name: 'Sonora', value: 'SONORA' },
  { name: 'Tabasco', value: 'TABASCO' },
  { name: 'Tamaulipas', value: 'TAMAULIPAS' },
  { name: 'Tlaxcala', value: 'TLAXCALA' },
  { name: 'Veracruz', value: 'VERACRUZ' },
  { name: 'Yucatán', value: 'YUCATAN' },
  { name: 'Zacatecas', value: 'ZACATECAS' },
];

export const plazos = [
  { name: '11', value: '10' },
  { name: '12', value: '20' },
  { name: '13', value: '30' },
  { name: '14', value: '40' },
  { name: '24', value: '56' },
  { name: '26', value: '80' },
  { name: '28', value: '82' },
  { name: '35', value: '110' },
];

export const days = [
  'Domingo',
  'Lunes',
  'Martes',
  'Miércoles',
  'Jueves',
  'Viernes',
  'Sábado',
];
