name: CI CD workflow
on:
  push:
    branches:
      - staging
      - development
jobs:
  CI:
    runs-on: ubuntu-latest
    env:
      PRODUCTION: ${{secret.PRODUCTION}}
      ENV_NAME: ${{secret.ENV_NAME}}
      API_URL: ${{secret.API_URL}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Print
        run: echo "$PRODUCTION and $ENV_NAME"

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.1
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4.0.0
        name: Setup pnpm cache
        with:
          path: |
            ${{ env.STORE_PATH }}
            ~/.cache/Cypress
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Linting
        run: npm run lint:ci

      - name: Unit Testing
        run: npm run test:ci

      - name: E2E Testing
        run: npm run e2e:ci
