name: CI CD workflow
on:
  push:
    branches:
      - staging
      - development
jobs:
  Continuous_Integration:
    runs-on: ubuntu-latest
    env:
      NG_APP_PRODUCTION: ${{secrets.NG_APP_PRODUCTION}}
      NG_APP_ENV_NAME: ${{secrets.NG_APP_ENV_NAME}}
      NG_APP_API_URL: ${{secrets.NG_APP_API_URL}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.1
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4.0.0
        name: Setup pnpm cache
        with:
          path: |
            ${{ env.STORE_PATH }}
            ~/.cache/Cypress
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Linting
        run: npm run lint:ci

      - name: Unit Testing
        run: npm run test:ci

      - name: E2E Testing
        run: npm run e2e:ci
